print("****************************************************")
print("                     ★ LAUNDRIFY ★                 ")
print("****************************************************")
print("                    ✦  Kelompok 2  ✦             ")
print("----------------------------------------------------")
print("   -Muhamad Adli Akbar                              ")
print("   -Novaka Rizky Heny Saputra                       ")
print("   -Restu Aji Prasetyo                              ")
print("   -Rifky Al Adli                                   ")
print("   -Arya Luqmannul Hakim                            ")
print("****************************************************")
